# 1. Cấu hình Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Đường dẫn kết nối (JDBC URL)

spring.datasource.url=jdbc:mysql://garment-db-hcmut-19b9.h.aivencloud.com:14816/defaultdb?ssl-mode=REQUIRED

# 3. User & Pass
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Kz3ebkN8PsUEV5NfkII

# 4. Cấu hình JPA 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect